# Generated by Django 5.2.9 on 2025-12-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammemberpage',
            name='role',
            field=models.CharField(blank=True, choices=[('host', '主办律师'), ('chief_assistant', '律师主任助理'), ('business_assistant', '律师业务助理')], max_length=32),
        ),
    ]
