# Generated by Django 5.2.9 on 2025-12-06 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_about_intro_homepage_main_lawyer_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='请输入有效的手机号码', regex='^1[3-9]\\d{9}$')], verbose_name='手机号码')),
                ('case_description', models.TextField(verbose_name='案情描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('is_processed', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('notes', models.TextField(blank=True, verbose_name='处理备注')),
            ],
            options={
                'verbose_name': '案情咨询',
                'verbose_name_plural': '案情咨询',
                'ordering': ['-created_at'],
            },
        ),
    ]
